### ISSUE TITLE
SYMBOL_ITERATOR is not defined

### ISSUE THREAD

**Issue by drejohnson** [pbastowski/angular-meteor-babel#1]
I'm not sure why this happens but it doesn't give this error on grigio's babel.
ReferenceError: SYMBOL_ITERATOR is not defined

**Comment by pbastowski** [comment]
I have pushed an update to Atmosphere and Github. Please try **meteor update** in your app directory. 

Sorry, that was my bad. I pushed the first version of the package with an error in package.js, somehow. This was my first meteor package :)

**Comment by pbastowski** [comment]
@drejohnson so, is it working for you now? I'd like to close this issue if it is resolved.

**Comment by drejohnson** [comment]
Yes, it works now. Thanks!
