### ISSUE TITLE
Unable to debug es2015 code correctly via source maps

### ISSUE THREAD

**Issue by mgrivera** [pbastowski/angular-meteor-babel#11]
Hi all, 

I've just posted this issue in angular-meteor (github issue #878), but with no success. 
This is my issue: I just want to configure _angular-babel_ to transpile my code, of course, _but_ to use source maps correctly, so when I debug my js code in chrome I can see my js2015 code and not the transpiled code (ie: es5 code). 

For example: if I write this line of code in my js file: 

``` javascript
let a = 1; 
```

I don't want to see: 

``` javascript
var a = 1; 
```

in chrome debugger. 

So, my question is: how do I have to write **babel.json** to have this? 

Currently, I have tried using this settings in babel.json: 

``` javascript
}
    "sourceMaps": "both",
    "extensions": ["js"] 
}
```

But I have this error when running my app: 

> c:\contabm.meteor\local\build\programs\server\app\server\lib\app.js:8
>  if (user.emails && _.some(user.emails, (email) => { return email.address ===
>                                                   ^
> SyntaxError: Unexpected token >
>    at c:\contabm.meteor\local\build\programs\server\boot.js:241:30
>    at Array.forEach (native)
>    at Function._.each._.forEach (C:\Users\Personal\AppData\Local.meteor\packages\meteor->tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server->lib\node_modules\underscore\underscore.js:79:11)
>    at c:\contabm.meteor\local\build\programs\server\boot.js:137:5
> Exited with code: 8
> Your application is crashing. Waiting for file change.

Can somebody please help? Thanks and bye ...

**Comment by pbastowski** [comment]
There is an issue with sourcemaps not working currently, which I am investigating.

Re your babel.json example above, the opening brace `}` is facing the wrong direction. It should be `{`.

**Comment by pbastowski** [comment]
Ok, I think I have it fixed now, with inline sourcemaps.

Please add `angular-bebel` explicitly to your project, like this

```
meteor add pbastowski:angular-babel@1.0.7
```

and let me know if that helped.

**Comment by mgrivera** [comment]
@pbastowski Hi and thanks for answering this issue. I saw your answer to this same question on _angular-meteor_ forum, issue #878. 

As I said there, I'm on vacations now (very short ones). So I'll check when arriving. 

Again, many thanks for your efforts and bye ... 

PD: looking forward to see my es2015 code when debugging on google chrome ...

**Comment by pbastowski** [comment]
As I said in the meteor forum issue, I can't replicate your problem on a Mac or on Windows. In both environments I see the ES6 code, as expected, not the transpiled code.

**Comment by mgrivera** [comment]
Hi @pbastowski, 
I've been reading some info regarding this issue. There is a _workspace_ option in chrome debugging tools settings: _settings - workspace - folders_. 

Do you think I can solve my issue if I add an entry in this form? There is an option to add a _folder_ and an option to add _options_ for the folder you added. Maybe by adding a folder and then its options Google Chrome will find and apply source mappings while debugging. 

What do you think? Could you please tell me what folder do I have to put in this setting? I just don't know where the meteor building process put all the files in the final bundle. 

Many thanks for your help and bye ...

**Comment by pbastowski** [comment]
I can't see how this is going to help, actually. Could you try the same repo in Firefox, just to see if it has perhaps something to do with your Chrome installation?

**Comment by pbastowski** [comment]
Actually, forget about my previous suggestion. I forgot that it doesn't work with FireFox.

**Comment by mgrivera** [comment]
Well, I just receive a number of this type of warning when running my program in chrome: 

> Source map http://localhost:3000/app/client/lib/_app.js?0d6585d183020e027787ea0ec72877b5c3685c16 points to the files missing from the workspace: 
> [http://localhost:3000/client/lib/_app.js]

So I supposed it could have to do with setting a folder where chrome developer tools could find the sources and resolve the mappings. 

Maybe it is not the correct path to solve the issue ...

**Comment by pbastowski** [comment]
I have something for you that may help. It's a new branch of angular-babel with source-maps in separate files. I hope this helps you, but we'll need to test this to find out for sure.

First, stop your meteor application. Then do the following:
1. `cd` to your project's root folder.
2. `mkdir packages && cd packages`
3. `git clone https://github.com/pbastowski/angular-meteor-babel.git`
4. `cd angular-meteor-babel`
5. `git checkout feature/server-systemjs-sourcemaps`
6. `cd` to your project's root folder.
7. `cd .meteor`
   8 delete the `local` folder and all it's contents

Step 8 deletes all the temporary build files that Meteor creates. We need this to ensure there is no code hanging around from the previous version, before we try the new version.

Now, start your meteor app again and see if it helped.

**Comment by mgrivera** [comment]
@pbastowski, Wow, you did it!! 
I'm, finally, seeing my (es6) code in chrome debugger. Many thanks and _congratulations_. Issue corrected. 

Now tell me: I think this is going to be a final (next) version some time. Maybe this is going to be in the **next** version of angular-babel? (I hope so)

Again, many thanks for all your help. It is very appreciated here. Bye ...

**Comment by pbastowski** [comment]
Yes, I will release this change in an upcoming version.
