### ISSUE TITLE
version 1.0.8 screws up causes check/match.js to throw errors for string _id values

### ISSUE THREAD

**Issue by DrDanRyan** [pbastowski/angular-meteor-babel#14]
This is probably related to the other polyfill issues, but since upgrading to 1.0.8 my app crashes on any subscription complaining that the Meteor generated string _id does not pass the check/match.js test. If I explicitly install pbastowski:angular-babel and move it to the top of my packages list, the issue goes away.

I also had to uninstall meteortoys:allthings to get the app to run correctly since upgrading to 1.0.8; probably a similar issue.

**Comment by pbastowski** [comment]
@DrDanRyan Sorry to hear about the problems you're encountering with v1.0.8. Is this in client or server code?

As a workaround, for now, you can downgrade to 1.0.7 by doing this

```
meteor add pbastowski:angular-babel@1.0.7
```

**Comment by niceilm** [comment]
https://github.com/Urigo/angular-meteor have this same problem.
So it was resolved by downgrading to 1.0.7.

**Comment by pbastowski** [comment]
@niceilm did you get this problem on the client or the server side code?

Also, for a workaround that does not involve downgrading to 1.0.7, could you please try putting `pbastowski:angular-babel` as the first package in your `.meteor/packages` file? Mostly this package is below other packages and moving it to the top, before `check` for instance, seems to fix the problem without having to downgrade.

**Comment by bmanturner** [comment]
Also had this issue (server-side). Your fix works for now. Thanks.

**Comment by pbastowski** [comment]
@niceilm @DrDanRyan @bmanturner  I have published angular-babel v1.0.9, which other users tell me has fixed the problem for them. Please let me know if it fixes your issue also. Thanks.

**Comment by bmanturner** [comment]
Can confirm this fixed all my issues!

**Comment by pbastowski** [comment]
@bmanturner thanks.
