### ISSUE TITLE
Problem when using with Meteor 1.3

### ISSUE THREAD

**Issue by Urigo** [pbastowski/angular-meteor-babel#16]
Hi friend!

When using the package with Meteor 1.3 and removing `ecmascript` we get an error immediately:

```
W20160319-13:26:01.565(2)? (STDERR)           
W20160319-13:26:01.565(2)? (STDERR) /Users/urigoldshtein/code/meteor-original-clone/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160319-13:26:01.566(2)? (STDERR)                                             throw(ex);
W20160319-13:26:01.566(2)? (STDERR)                                                   ^
W20160319-13:26:01.574(2)? (STDERR) ReferenceError: require is not defined
=> Exited with code: 8                      
```

Steps to reproduce - create a new Meteor 1.3 app with the latest RC.
remove `ecmascript` and add `pbastowski:angular-babel` and run the app.

thanks!

**Comment by Urigo** [comment]
Ohhh and I guess adding `modules` solves it, so maybe the only thing needs to be done is to add it as a dependency - https://github.com/Urigo/angular-meteor/issues/1277#issuecomment-198752692

**Comment by pbastowski** [comment]
Hi Uri. I'll look into this now.

**Comment by pbastowski** [comment]
@Urigo 
It appears that you are correct, in that we just need the `modules` package as a dependency. I will create a special Meteor 1.3 release of angular-babel.

Hey, did I notice correctly that Meteor's native `ecmascript` package will not get decorators with Meteor 1.3? (see https://github.com/meteor/meteor/issues/6057)

**Comment by pbastowski** [comment]
@Urigo 

OK, it's done. See pbastowski:angular-babel@1.3.1  https://atmospherejs.com/pbastowski/angular-babel

If you currently have my package in your project then please remove it first and then re-add it back. Also, in case you are interested, I updated my typescript package in the same way.
