### ISSUE TITLE
Problem with default variables

### ISSUE THREAD

**Issue by sebakerckhof** [pbastowski/angular-meteor-babel#17]
I upgraded `meteor-angular` to 1.3.7, which upgraded `pbastowski:angular-babel` to 1.0.9.
Since then, I have errors with functions that have default variable values:

I have a function like:

``` js
function myFunction(foo,bar = "defaultValue"){
...
}
```

With `pbastowski:angular-babel@1.0.9`, this gets transpiled to:

``` js
var _temporalUndefined = {};                                                                                         
function myFunction(foo) {                                                               
  var foo = _temporalUndefined;                                                                               
  var bar = _temporalUndefined;                                                                                      
  foo = arguments.length <= 0 || arguments[0] === undefined ? undefined : arguments[0];                        
  bar = arguments.length <= 1 || arguments[1] === undefined ? "defaultValue" : arguments[1]; 
...
}
```

This is of course incorrect, since a call like:

``` js
myFunction("baz")
```

Will assign `{}` to variable `foo`.

Minimal reproduction: https://github.com/sebakerckhof/meteor-angular-babel-problem

Edit: If I manually clone your meteor1.2 branch, everything works fine. If I get the package from atmosphere, I have this problem... Could there be a wrong version uploaded to atmosphere?

**Comment by sebakerckhof** [comment]
Nevermind, the cached package downloaded by meteor was corrupt due to a hard drive issue. Removing the cached package solved this problem.

**Comment by pbastowski** [comment]
@sebakerckhof 
Nice one :) The best issues close themselves! 
Thanks for providing your solution.
