### ISSUE TITLE
Babel transformation breaks `$scope.$meteorCollection(<collection>).find`

### ISSUE THREAD

**Issue by gabehayes** [pbastowski/angular-meteor-babel#2]
While I believe that I am aware of the root cause of the issue, I'm not entirely sure _which package_ the issue exists in.

Basically, I have an app running with the following packages enabled:

```
pbastowski:angular-babel
pbastowski:angular2-now
```

When I attempt to do a find on a collection from the client with:

```
$scope.$meteorCollection(<GlobalCollectionName>).find({})
```

I get the following error:

```
Uncaught TypeError: [object Object] is not a function!
```

When I attempt to do a find on a collection from the client with:

```
<GlobalCollectionName>.find({})
```

I successfully get the expected Mongo cursor back.

When logging out the two find methods, I expected them to be the same thing, but I discovered this difference:

```
$scope.$meteorCollection(<GlobalCollectionName>).find
> 3.module.exports(callbackfn)

<GlobalCollectionName>.find
> _.extend.find()
```

Which I was then able to trace back to [this section](https://github.com/pbastowski/angular-meteor-babel/blob/master/lib/core-js-no-number.js#L58-L67) of core-js.

It looks like when the babel transformation occurs, that bit of code is overriding the `find` method of the `$meteorCollection`.

Again, not entirely sure which package is at fault, but I thought you could at least help do some more debugging here.

Thanks for looking into this, and great work with angular2-now! It feels great to be able to write angular2-ish code with all of the reliability of angular1.

**Comment by pbastowski** [comment]
The statement 

``` javascript
$scope.$meteorCollection(<GlobalCollectionName>)
```

returns an Array, not a Mongo/FS collection. That is why `find({})` does not work on it. The find method that is attached to the Array object expects a callback as an argument, not an object literal.

> In the example below, I am using a FS.Collection. But you could use a Mongo.Collection also.

In your browser's DEV console try the following. Change Images to the name of your global object.

``` javascript
$scope.$meteorCollection(Images) instanceof Array
true

Images instanceof FS.Collection
true
```

On the other hand, `<GlobalCollectionName>` returns a Mongo/FS cursor. The find method of a Mongo/FS cursor knows how to handle literal objects as its argument.

Does this help you?

**Comment by gabehayes** [comment]
Yes, this makes total sense. I was under the impression that the `find` method of a `$meteorCollection` would return the Mongo cursor, but after digging into the docs a bit more I see where I am going wrong.

I should be using `publish` on the server to publish a filtered results and `subscribe` on the `$meteorCollection` in the client to watch those results.

I was attempting to do that `find` and filter the items client side, but the [example here](http://angular-meteor.com/api/meteorCollection) clears that up a bit.

Thanks for helping out with this!
