### ISSUE TITLE
Babel Note about browser-polyfill-old.js

### ISSUE THREAD

**Issue by mxab** [pbastowski/angular-meteor-babel#22]
When I build my program I get:

```
[BABEL] Note: The code generator has deoptimised the styling of "/packages/pbastowski_angular-babel/lib/browser-polyfill-old.js" as it exceeds the max of "100KB".
```

Not sure what it means and if it is ok :)

**Comment by pbastowski** [comment]
Two answers: 
1) It's just an info message from Babel that can be safely ignored. 
2) I will investigate why it mentions a "-old.js" 

Thanks for reporting this.

**Comment by pbastowski** [comment]
@mxab 
I just published v1.3.3, which no longer shows the Babel Note. 

Let me know if this helped.

**Comment by mxab** [comment]
hi, 
my build looks ok, the message is gone. 

Unfortunately the build still takes about 10 mins but I guess it does not relate to this

Thanks

**Comment by pbastowski** [comment]
Thanks for checking.

wow, 10 mins. Was it also taking this long with Meteor 1.2?

**Comment by mxab** [comment]
I'm not 100% sure but I would say that it felt a bit faster, any ideas?

**Comment by mxab** [comment]
one thing i did with my 1.2 version was that I loaded a lot of libs like jquery, angular, angular-XXX via cdn maybe this had some effect on the minification process

**Comment by pbastowski** [comment]
Using CDNs would definitely have had an impact, because there would have been no need to minimise all those libraries. How many JS files do you have in your project?

**Comment by mxab** [comment]
about 450 js files

**Comment by mxab** [comment]
sorry thats wrong 450 html+js files

**Comment by mxab** [comment]
138 html
 311 js
 16 less
