### ISSUE TITLE
Errors prevented startup: pbastowski:angular-babel... Babel transform error

### ISSUE THREAD

**Issue by MinhTri66** [pbastowski/angular-meteor-babel#23]
Hello thank you so much for the awesome package. I am following this tutorial: http://www.angular-meteor.com/tutorials/socially/angular1/3-way-data-binding

At the **3.3  Add some data to the parties collection server/startup.js**

> Meteor.startup(() =&gt; {
>   if (Parties.find().count() === 0) {
>     const parties = [{
>       'name': 'Dubstep-Free Zone',
>       'description': 'Fast just got faster with Nexus S.'
>     }, {
>       'name': 'All dubstep all the time',
>       'description': 'Get it on!'
>     }, {
>       'name': 'Savage lounging',
>       'description': 'Leisure suit required. And only fiercest manners.'
>     }];
> 
> ```
> parties.forEach((party) =&gt; {
>   Parties.insert(party)
> });
> ```
> 
>   }
> });

After I make startup.js file in the server/ folder and insert above code, then the browser returned error:

> Your app is crashing. Here's the latest log:
> Started MongoDB.
> Errors prevented startup:
> 
> While processing files with pbastowski:angular-babel (for target os.windows.x86_32):
> server/startup.js:1:18: Babel transform error
> 
> Your application has errors. Waiting for file change.

I am using window7 ultimate 64bit and the meteor 1.3. I have removed blaze-html-templates and removed ecmascript follow the tutorial at the first step.

Can anyone help me please... 
Thanks in advance.

**Comment by pbastowski** [comment]
In the fragment of code below

```
parties.forEach((party) =&gt;
```

Try replacing `&gt;` with `>`.

**Comment by MinhTri66** [comment]
OMG... it's a simple issue with a simple fix. I didn't realize this sooner. Thank you very much, everything works like a charm now :+1:

**Comment by pbastowski** [comment]
You are welcome :)
