### ISSUE TITLE
chrome inspector is stopping at babel compiler

### ISSUE THREAD

**Issue by dohomi** [pbastowski/angular-meteor-babel#24]
Hi
we are currently investigating why on hot code push open tabs of our app are constantly reloading after code changes and re-deploy. I have the feeling one issue could depend on this plugin, if I enable `Pause on caught Exceptions`in Chrome debugger I find this error:

```
TypeError: Iterator result undefined is not an object at Function.all (native) at 
```

Its very hard to know where this error belongs but have you experienced this by any chance?

**Comment by pbastowski** [comment]
No, I haven't see this error myself.

Just thinking, what is `Function.all`? I know there is a `Function.call()` method.

**Comment by dohomi** [comment]
We will try to investigate further. It seems to be a polyfill issue somewhere in the code but its almost impossible to track it down. I come back if it really belongs to your plugin.

**Comment by mkristo** [comment]
@dohomi: Just out of curiosity, did you ever come to any conclusion what was causing this? I'm seeing the same behavior currently. I'm not using angular-meteor-babel though.

**Comment by jgwconsulting** [comment]
Yes,I am as well, using React.

**Comment by jgwconsulting** [comment]
Possibly related:
- https://github.com/zloirock/core-js/issues/186
- https://bugs.chromium.org/p/v8/issues/detail?id=5057

**Comment by dohomi** [comment]
@mkristo at the moment there seems some additional chrome and firefox issues. I haven't really worked it out - waiting for a Meteor update because currently my sourcemap also doesn't work as expected any longer

**Comment by mkristo** [comment]
So, I've managed to prevent the issue from happening in my project. I was using babel-polyfill v 6.5.0. The code that started the Chrome Inspector debugger was (in Promise-related code)

```
  P.all(iter)['catch'](function(){});
```

My guess is that Chrome doesn't recognize that as a catched exception, and thus pauses execution.

The solution for me was to simply bump babel-polyfill to the latest version, which is v 6.9.1 as I'm writing this.

I understand this has nothing to do with angular-meteor-babel, so I'm sorry for spamming your project. :blush: But hopefully this workaround will help someone.

**Comment by vzaidman** [comment]
+1

**Comment by ericsoco** [comment]
@mkristo seems to have nailed it. bumping `babel-polyfill` from 6.7.2 to latest (`6.9.1`) fixed the debugger stop for me.

FWIW, this has nothing to do with Angular or Meteor or React. It's just a `babel-polyfill` thing.
