### ISSUE TITLE
Angular server service not working correctly when using angular-meteor-babel instead of ecmascript

### ISSUE THREAD

**Issue by Ben305** [pbastowski/angular-meteor-babel#26]
I have a Meteor application (running currently 1.3.4.1) using Angular-Meteor (Angular 1.5.x) and Angular-Meteor-Server (https://github.com/netanelgilad/angular-meteor-server). When Meteor 1.3 was released, I started to write code in ES6 and I've reached the point where the packages that contain the server side angular services are ready to be rewritten in ES6.

Now I have a package which contains some client code, and some angular-server side services, so I have to use `angular-meteor-babel` instead of `ecmascript`. This hasn't been a problem, but using `angular-meteor-babel` leads to problems when I try to use an angular server side on the client that has been written in ES6.

I have prepared a sample application to demonstrate the problem. You can find it here: https://github.com/Ben305/ES6AngularServer 
The application structure is very simple: There's a package that contains an ES6 angular server side service, nothing else. This service get's injected into the main application. Everything works well, when the package uses `ecmascript`. When I remove `ecmascript` from `package.js` and replace it with `angular-meteor-babel`, the service can be injected in the client, but has no functions. I have no idea what's wrong there, but if I can help feel free to ping me.

**Comment by pbastowski** [comment]
@ben305
I'm on holidays right now. If you can wait 10 days or so then I wi try to help you, once I get back.

**Comment by Ben305** [comment]
@pbastowski Enjoy the holidays, this can wait until you're back!

**Comment by pbastowski** [comment]
@Ben305 Is this still a problem for you?

**Comment by Ben305** [comment]
@pbastowski Yes, nothing has changed. The sample is still up to date.

**Comment by pbastowski** [comment]
@Ben305 I'm sorry, but I'm too busy with projects still to look at this issue. Also, I don't use angular server for anything, which doesn't help me in tracking the problem down. 

Have you tried just using `Meteor.methods({ ... })` instead? Also, I use `Tracker.Autorun()` on the front-end to catch changes to data in my database collections.
