### ISSUE TITLE
Error on meteor update

### ISSUE THREAD

**Issue by nickovchinnikov** [pbastowski/angular-meteor-babel#28]
```
=> Errors while initializing project:         

While loading plugin `compileNGScript` from package `pbastowski:angular-babel`:
packages/compileNGScript/plugin/ng-script-compiler.js:145:1: Object [object
Object] has no method 'existsSync'
at getCustomConfig
(packages/compileNGScript/plugin/ng-script-compiler.js:145:1)
at Package (packages/compileNGScript/plugin/ng-script-compiler.js:27:1)
at <runJavaScript-59>:170:4
at <runJavaScript-59>:177:3
```

**Comment by pbastowski** [comment]
@master-7 
You did not specify what version of Meteor you are updating to or from, so, it's difficult to tell what the error might be related to. However, assuming that you're updating to Meteor 1.3.x, it's probably just left over cached stuff.

Try deleting the `.meteor/local` folder. Usually this helps. 

In your project's root folder type this at the command line:

```
rm -rf .meteor/local
```

If the above did not help, then please provide me a lot more information about your project and environment, such as Meteor versions, package versions, OS type, link to your project on github, etc.

**Comment by nickovchinnikov** [comment]
meteor --version
Meteor 1.3.2.4 

Start the upgrade to Meteor 1.3.4.4

I try the delete .meteor/local its not works

**Comment by pbastowski** [comment]
Are on Windows, Linux or OS X?

If on OS X then try try deleting it this way

```
cd .meteor
rm -rf local
```

**Comment by nickovchinnikov** [comment]
Ubuntu, and am run 
`sudo rm -r .meteor/local`

**Comment by pbastowski** [comment]
Ok, thanks. Please try my suggestion above with two separate lines.

**Comment by pbastowski** [comment]
Also, what error message do you get when you try to delete?

**Comment by nickovchinnikov** [comment]
No error message - directory is deleted and this all. Next im run the meteor update and problem repeated

**Comment by pbastowski** [comment]
Very strange, because that's normally all you need to do to fix this issue.

Can you please push your repo to github and then I can clone it and try and help you?

If you can't push the same repo then  try to replicate the problem in a new project and push that to github.

**Comment by nickovchinnikov** [comment]
Im view the message
`* pbastowski:angular-babel 1.0.9 (1.3.6 is available)`
Am change the version angular-babel in file .meteor/versions and meteor update went well.
Fixed, and thank you very much for your help!

**Comment by pbastowski** [comment]
Good to hear :)
