### ISSUE TITLE
Cordova app breaks

### ISSUE THREAD

**Issue by hlehmann** [pbastowski/angular-meteor-babel#3]
Hi,
After deploying browser version works well but cordova version breaks.
It seems to be the files order that is not well respected (lib dir first).

**Comment by pbastowski** [comment]
Can you please provide more detail re the problem? A repo that duplicates the issue will help.

What version of Meteor are you using?

Do you get an error? If yes then please share it here.

Thanks.

**Comment by pbastowski** [comment]
I'm closing this issue. Reopen if need be
