### ISSUE TITLE
Meteor 1.4 version with reify

### ISSUE THREAD

**Issue by sebakerckhof** [pbastowski/angular-meteor-babel#32]
Since Meteor 1.4, Meteor supports nested imports through https://github.com/benjamn/reify
When using angular with this plugin, one looses this ability...

**Comment by pbastowski** [comment]
True. I have no idea how to integrate reify into angular-babel. Do you?

Also, are nested imports an industry standard or just a Meteor/reify feature?

**Comment by sebakerckhof** [comment]
It's not industry standard. It's a reify feature, but it can be used outside of Meteor (not outside of reify).

I first thought it was just a babel plugin, but apparently it works different.
It's a runtime library you need to include in your application. This is done by the Meteor 'modules' package. Since this package uses the modules package I don't understand why this doesn't work. Maybe one also needs to change a Babel setting? Or maybe it's because Meteor uses Babel 6 instead of 5? I'll look into it further when I got time.

**Comment by pbastowski** [comment]
I'm closing this issue, since I no longer support this package. I still have to add a deprecation warning to the readme.
