### ISSUE TITLE
Add options to prevent Babel from listing all files its compiling

### ISSUE THREAD

**Issue by ShimShamSam** [pbastowski/angular-meteor-babel#6]
Since switching to this package, Babel outputs the name of every file it compiles. Is there any way to turn this off? I tried setting "verbose" to false in the settings but that didn't help.

**Comment by pbastowski** [comment]
I've updated the package to 1.0.3. From the README:

## Custom configuration with .babelrc

Place `.babelrc` at the root of your project to override certain default settings. This file is completely optional and may contain the following in JSON format. The values below are the default configuration.

```
{
    "verbose": false,     // true shows files being compiled
    "debug": false,       // true displays this config file
    "modules": "common",  // what module format Babel should use. See 
                          // Babel documentation for "modules" option.
    "blacklist": ['useStrict'],  // Do not change this unless you know
                                 // very well what you are doing.
    "stage": 0            // see Babel documentation for stage option.
}
```

**Comment by ShimShamSam** [comment]
The README on GitHub has not been updated. So do I replace my babel.json with .babelrc or is one for the package and one for Babel's actual runtime?

**Comment by pbastowski** [comment]
I see what you are referring to :) The meteor1.2 branch has it's own readme https://github.com/pbastowski/angular-meteor-babel/tree/meteor1.2

There is just the .babelrc for Meteor 1.2 version. There is no more babel.json. So, yes, rename `babel.json` to `.babelrc` and then restart meteor.

**Comment by pbastowski** [comment]
Also, on Atmosphere you get the latest README for Meteor 1.2 https://atmospherejs.com/pbastowski/angular-babel

**Comment by pbastowski** [comment]
Closing this issue. If you still have problems specifically with Babel listing all the files it is compiling then feel free to reopen.
