### ISSUE TITLE
package collision with universe:ecmascript

### ISSUE THREAD

**Issue by thinkrapido** [pbastowski/angular-meteor-babel#9]
I've upgraded to meteor 1.2.1 and have the following issue:

```
error: conflict: two packages included in the app (pbastowski:angular-babel and universe:ecmascript) are both
   trying to handle *.js
```

What can I do?

**Comment by pbastowski** [comment]
Try removing `universe:ecmascript` from your project and see if that helps.

```
meteor remove universe:ecmascript
```

`pbastowski:angular-babel` comes bundled with angular-meteor and can't be removed without removing `angular` from your project.

**Comment by pbastowski** [comment]
I just remembered this: if you really need to use `universe:ecmascript`, or any other JS handler that wants to compile ".js" files, then you can configure `pbastowski:angular-babel` to not compile ".js" files by adding the line below to **babel.json** in your Meteor project's root folder. 

**babel.json**

``` javascript
{
    "extensions": ["es6.js"]
}
```

This will instruct `angular-babel` to only compile JavaScript files with the extension ".es6.js", removing the conflict with other packages that implement handlers for ".js" files.

I hope this helps you.

**Comment by mgrivera** [comment]
Hi all, 

I've tried this and it works. I mean: 
1. add _babel.json_ as @pbastowski just said 
2. add _ecmascript_ package 
3. run your meteor app 
4. there won't be any conflict between _angular-babel_ and _ecmascript_ because angular-babel won't compile (ie: transpile) js files; ecmascript will. 

bye ...

**Comment by pbastowski** [comment]
But if you do this some ES7 features will be missing, such as decorators, which are required for angular2-now, for example.
